### PR TITLE
Write fields and properties

### PR DESCRIPTION
**Pull request by Senkey28**

### CODE REVIEW

**Comment by ChaisStar** [comment]
Nice work, but it's not quite what I asked for. 
I don't know exactly how you suppose to use those properties in the "Program" class, you will tell me later. 
What you need to do is you need to create a separated class in the new "cs" file with properties that describe all that you want to save into the database

**Comment by ChaisStar** [comment]
For example, [here ]( https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-5.0&pivots=server ) you can see how class TodoItem is described

**Comment by Senkey28** [comment]
That is, I have make changes and repeat pull request?

**Comment by ChaisStar** [comment]
You have to change the code, create a new commit and push it to GitHub. This pull request will be updated automatically according to your last commit.

**Pull request merged**
